class Autogenerated {
  int? code;
  Data? data;
  bool? success;

  Autogenerated({this.code, this.data, this.success});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    success = json['success'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['success'] = this.success;
    return data;
  }
}

class Data {
  int? ownerId;
  String? fullName;
  String? ownerFaceImage;
  String? relationship;
  String? gender;
  int? bikeId;
  String? updatedAt;
  String? createdAt;

  Data(
      {this.ownerId,
      this.fullName,
      this.ownerFaceImage,
      this.relationship,
      this.gender,
      this.bikeId,
      this.updatedAt,
      this.createdAt});

  Data.fromJson(Map<String, dynamic> json) {
    ownerId = json['ownerId'];
    fullName = json['fullName'];
    ownerFaceImage = json['ownerFaceImage'];
    relationship = json['relationship'];
    gender = json['gender'];
    bikeId = json['bikeId'];
    updatedAt = json['updatedAt'];
    createdAt = json['createdAt'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['ownerId'] = this.ownerId;
    data['fullName'] = this.fullName;
    data['ownerFaceImage'] = this.ownerFaceImage;
    data['relationship'] = this.relationship;
    data['gender'] = this.gender;
    data['bikeId'] = this.bikeId;
    data['updatedAt'] = this.updatedAt;
    data['createdAt'] = this.createdAt;
    return data;
  }
}