class Autogenerated {
  int? code;
  List<Data>? data;
  bool? success;

  Autogenerated({this.code, this.data, this.success});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
    success = json['success'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['success'] = this.success;
    return data;
  }
}

class Data {
  int? bikeId;
  String? fullname;
  String? username;
  String? gender;
  String? age;
  String? address;
  int? userId;
  String? createdAt;
  String? updatedAt;
  dynamic cardId;

  Data(
      {this.bikeId,
      this.fullname,
      this.username,
      this.gender,
      this.age,
      this.address,
      this.userId,
      this.createdAt,
      this.updatedAt,
      this.cardId});

  Data.fromJson(Map<String, dynamic> json) {
    bikeId = json['bikeId'];
    fullname = json['fullName'];
    username = json['username'];
    gender = json['gender'];
    age = json['age'];
    address = json['address'];
    userId = json['userId'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    cardId = json['cardId'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['bikeId'] = this.bikeId;
    data['fullName'] = this.fullname;
    data['username'] = this.username;
    data['gender'] = this.gender;
    data['age'] = this.age;
    data['address'] = this.address;
    data['userId'] = this.userId;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['cardId'] = this.cardId;
  
    return data;
  }
}