class Autogenerated {
  int? code;
  List<Data>? data;
  bool? success;

  Autogenerated({this.code, this.data, this.success});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
    success = json['success'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['success'] = this.success;
    return data;
  }
}
class Data {
  int? notificationId;
  String? message;
  //dynamic approvedBy;
  String? notificationType;
  String? createdAt;
  String? updatedAt;
  int? userId;

  Data(
      {this.notificationId,
      this.message,
      this.notificationType,
      this.createdAt,
      this.updatedAt,
      this.userId,
});

  Data.fromJson(Map<String, dynamic> json) {
    notificationId = json['notificationId'];
    message = json['message'];
    notificationType = json['notificationType'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    userId = json['userId'];
   

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['notificationId'] = this.notificationId;
    data['message'] = this.message;
    data['notificationType'] = this.notificationType;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['userId'] = this.userId;
    return data;
  }
}
