class Autogenerated {
  int? code;
  List<Data>? data;
  bool? success;

  Autogenerated({this.code, this.data, this.success});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
    success = json['success'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['success'] = this.success;
    return data;
  }
}
class Data {
  int? ownerId;
  String? fullName;
  //dynamic approvedBy;
  String? gender;
  String? relationship;
  String? ownerFaceImage;
  String? plateNumber;
  String? createdAt;
  String? updatedAt;
  int? bikeId;

  Data(
      {this.ownerId,
      this.fullName,
      this.gender,
      this.relationship,
      this.ownerFaceImage,
      this.plateNumber,
      this.createdAt,
      this.updatedAt,
      this.bikeId
});

  Data.fromJson(Map<String, dynamic> json) {
    ownerId = json['ownerId'];
    fullName = json['fullName'];
    gender = json['gender'];
    relationship = json['relationship'];
    ownerFaceImage = json['ownerFaceImage'];
    plateNumber = json['plateNumber'];

    createdAt = json['createdAt'];

    updatedAt = json['updatedAt'];

    bikeId = json['bikeId'];

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['bikeId'] = this.bikeId;
    data['fullName'] = this.fullName;
    data['gender'] = this.gender;
    data['relationship'] = this.relationship;
    data['ownerFaceImage'] = this.ownerFaceImage;
    data['plateNumber'] = this.plateNumber;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['gender'] = this.gender;
    data['bikeId'] = this.bikeId;
    return data;
  }
}
