class Autogenerated {
  int? code;
  List<Data>? data;
  bool? success;

  Autogenerated({this.code, this.data, this.success});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
    success = json['success'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['success'] = this.success;
    return data;
  }
}
class Data {
  int? parkingTypeId;
  String? parkingTypeName;
  String? parkingTypeStatus;
  String? parkingTypeGroup;
  String? parkingTypeFee;
  String? description;
  String? createdAt;
  String? updatedAt;
 

  Data(
      {this.parkingTypeId,
      this.parkingTypeName,
      this.parkingTypeStatus,
      this.parkingTypeGroup,
      this.parkingTypeFee,
      this.description,
      this.createdAt,
      this.updatedAt,
     
});

  Data.fromJson(Map<String, dynamic> json) {
    parkingTypeId = json['parkingTypeId'];
    parkingTypeName = json['parkingTypeName'];
    parkingTypeStatus = json['parkingTypeStatus'];
    parkingTypeGroup = json['parkingTypeGroup'];
    parkingTypeFee = json['parkingTypeFee'];
    description = json['description'];
    createdAt = json['createdAt'];

    updatedAt = json['updatedAt'];


  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['parkingTypeId'] = this.parkingTypeId;
    data['parkingTypeName'] = this.parkingTypeName;
    data['parkingTypeStatus'] = this.parkingTypeStatus;
   
    data['parkingTypeGroup'] = this.parkingTypeGroup;
    data['parkingTypeFee'] = this.parkingTypeFee;
    data['description'] = this.description;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
   
    return data;
  }
}
