class Autogenerated {
  int? code;
  List<Cards>? data;
  bool? success;

  Autogenerated({this.code, this.data, this.success});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    if (json['data'] != null) {
      data = <Cards>[];
      json['data'].forEach((v) {
        data!.add(new Cards.fromJson(v));
      });
    }
    success = json['success'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['success'] = this.success;
    return data;
  }
}
class Cards {
  String? cardId;


  Cards(
      {this.cardId,

});

  Cards.fromJson(Map<String, dynamic> json) {
    cardId = json['cardId'];

   

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['cardId'] = this.cardId;

    return data;
  }
}
