class Autogenerated {
  int? code;
  List<Data>? data;
  bool? success;

  Autogenerated({this.code, this.data, this.success});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
    success = json['success'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['success'] = this.success;
    return data;
  }
}
class Data {
  int? parkingSessionId;
  String? checkinTime;
  String? checkinCardId;
  String? checkoutCardId;
  String? checkoutTime;
  String? checkinFaceImage;
  String? checkoutFaceImage;
  String? checkinPlateNumberImage;
  String? checkoutPlateNumberImage;
  String? approvedBy;
  String? plateNumber;
  int? parkingFee ;
  String? createdAt;
  String? updatedAt;
  int? parkingTypeId;

  Data(
      {this.parkingSessionId,
      this.checkinTime,
      this.checkinCardId,
      this.checkoutCardId,
      this.checkoutTime,
      this.checkinFaceImage,
      this.checkoutFaceImage,
      this.checkinPlateNumberImage,
      this.checkoutPlateNumberImage,
      this.approvedBy,
      this.plateNumber,
      this.parkingFee,
      this.createdAt,
      this.updatedAt,
      this.parkingTypeId
      });

  Data.fromJson(Map<String, dynamic> json) {
    parkingSessionId = json['parkingSessionId'];
    checkinTime = json['checkinTime'];
    checkinCardId = json['checkinCardId'];
    checkoutCardId = json['checkoutCardId'];
    checkoutTime = json['checkoutTime'];
    checkinFaceImage = json['checkinFaceImage'];
    checkoutFaceImage = json['checkoutFaceImage'];
    checkinPlateNumberImage = json['checkinPlateNumberImage'];
    checkoutPlateNumberImage = json['checkoutPlateNumberImage'];
    approvedBy = json['approvedBy'];
    plateNumber = json['plateNumber'];
    parkingFee = json['parkingFee'] ?? 0;
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    parkingTypeId = json['parkingTypeId'] ?? 0;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['parkingSessionId'] = this.parkingSessionId;
    data['checkinTime'] = this.checkinTime;
    data['checkoutTime'] = this.checkoutTime;
    data['checkinCardId'] = this.checkinCardId;
    data['checkoutCardId'] = this.checkoutCardId;
    data['checkinFaceImage'] = this.checkinFaceImage;
    data['checkoutFaceImage'] = this.checkoutFaceImage;
    data['checkinPlateNumberImage'] = this.checkinPlateNumberImage;
    data['checkoutPlateNumberImage'] = this.checkoutPlateNumberImage;
    data['approvedBy'] = this.approvedBy;
    data['plateNumber'] = this.plateNumber;
   data['parkingFee'] = this.parkingFee;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['parkingTypeId'] = this.parkingTypeId;
    return data;
  }
}
