class Autogenerated {
  int? code;
  Data? data;
  bool? success;

  Autogenerated({this.code, this.data, this.success});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    success = json['success'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['success'] = this.success;
    return data;
  }
}

class Data {
  String? bikeId;
  String? parkingTypeId;
  String? plateNumber;
  String? parkingTypeName;
  String? expiredDate;
  String? parkingOrderAmount;
  String? createdAt;

  Data(
      {this.bikeId,
      this.parkingTypeId,
      this.plateNumber,
      this.parkingTypeName,
      this.expiredDate,
      this.parkingOrderAmount,
      this.createdAt});

  Data.fromJson(Map<String, dynamic> json) {
    bikeId = json['bikeId'];
    parkingTypeId = json['parkingTypeId'];
    plateNumber = json['plateNumber'];
    parkingTypeName = json['parkingTypeName'];
    expiredDate = json['expiredDate'];
    parkingOrderAmount = json['parkingOrderAmount'];
    createdAt = json['createdAt'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['bikeId'] = this.bikeId;
    data['parkingTypeId'] = this.parkingTypeId;
    data['plateNumber'] = this.plateNumber;
    data['parkingTypeName'] = this.parkingTypeName;
    data['expiredDate'] = this.expiredDate;
    data['parkingOrderAmount'] = this.parkingOrderAmount;
    data['createdAt'] = this.createdAt;
    return data;
  }
}