class Autogenerated {
  int? code;
  Data? data;
  bool? success;

  Autogenerated({this.code, this.data, this.success});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    success = json['success'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['success'] = this.success;
    return data;
  }
}

class Data {
  Registration? registration;
  int? amount;

  Data({this.registration, this.amount});

  Data.fromJson(Map<String, dynamic> json) {
    registration = json['registration'] != null
        ? new Registration.fromJson(json['registration'])
        : null;
    amount = json['amount'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.registration != null) {
      data['registration'] = this.registration!.toJson();
    }
    data['amount'] = this.amount;
    return data;
  }
}

class Registration {
  int? registrationId;
  String? registrationStatus;
  String? approvedBy;
  String? expiredDate;
  String? faceImage;
  String? plateNumber;
  String? model;
  String? registrationNumber;
  String? manufacture;
  String? gender;
  String? createdAt;
  String? updatedAt;
  int? userId;

  Registration(
      {this.registrationId,
      this.registrationStatus,
      this.approvedBy,
      this.expiredDate,
      this.faceImage,
      this.plateNumber,
      this.model,
      this.registrationNumber,
      this.manufacture,
      this.gender,
      this.createdAt,
      this.updatedAt,
      this.userId,
    
      });

  Registration.fromJson(Map<String, dynamic> json) {
    registrationId = json['registrationId'];
    registrationStatus = json['registrationStatus'];
    approvedBy = json['approvedBy'];
    expiredDate = json['expiredDate'] ?? "";
    faceImage = json['faceImage'];
    plateNumber = json['plateNumber'];
    model = json['model'];
    registrationNumber = json['registrationNumber'];
    manufacture = json['manufacture'];
    gender = json['gender'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    userId = json['userId'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['registrationId'] = this.registrationId;
    data['registrationStatus'] = this.registrationStatus;
    data['approvedBy'] = this.approvedBy;
    data['expiredDate'] = this.expiredDate;
    data['faceImage'] = this.faceImage;
    data['plateNumber'] = this.plateNumber;
    data['model'] = this.model;
    data['registrationNumber'] = this.registrationNumber;
    data['manufacture'] = this.manufacture;
    data['gender'] = this.gender;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['userId'] = this.userId;
    return data;
  }
}