class Autogenerated {
  int? code;
  List<Data>? data;
  bool? success;

  Autogenerated({this.code, this.data, this.success});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
    success = json['success'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['success'] = this.success;
    return data;
  }
}

class Data {
  int? registrationId;
  String? registrationStatus;
  //dynamic approvedBy;
  String? approvedBy;
  String? expiredDate;
  String? faceImage;
  String? plateNumber;
  bool? hasPayment;
  String? createdAt;
  String? updatedAt;
  int? userId;

  Data(
      {this.registrationId,
      this.registrationStatus,
      this.approvedBy,
      this.expiredDate,
      this.faceImage,
      this.plateNumber,
      this.hasPayment,
      this.createdAt,
      this.updatedAt,
      this.userId});

  Data.fromJson(Map<String, dynamic> json) {
    registrationId = json['registrationId'];
    registrationStatus = json['registrationStatus'];
    approvedBy = json['approvedBy'];
    expiredDate = json['expiredDate'];
    faceImage = json['faceImage'];
    plateNumber = json['plateNumber'];
    hasPayment = json['hasPayment'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    userId = json['userId'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['registrationId'] = this.registrationId;
    data['registrationStatus'] = this.registrationStatus;
    data['approvedBy'] = this.approvedBy;
    data['expiredDate'] = this.expiredDate;
    data['faceImage'] = this.faceImage;
    data['plateNumber'] = this.plateNumber;
    data['hasPayment'] = this.hasPayment;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['userId'] = this.userId;
    return data;
  }
}