class Autogenerated {
  int? code;
  List<Data>? data;
  bool? success;

  Autogenerated({this.code, this.data, this.success});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
    success = json['success'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['success'] = this.success;
    return data;
  }
}
class Data {

  int? registrationId;
  String? registrationStatus;
  //dynamic approvedBy;
  String? approvedBy;
  String? expiredDate;
  String? faceImage;
  String? plateNumber;
  String? createdAt;
  String? model;
  String? registrationNumber;
  String? manufacture;
  String? gender;
  String? updatedAt;
  int? userId;
  int? amount;

  Data(
      {this.registrationId,
      this.registrationStatus,
      this.approvedBy,
      this.expiredDate,
      this.faceImage,
      this.plateNumber,
      this.createdAt,
      this.updatedAt,
      this.model,
      this.registrationNumber,
      this.manufacture,
      this.gender,
      this.userId,
      this.amount});

  Data.fromJson(Map<String, dynamic> json) {
   // var f = DateFormat('E, d MMM yyyy HH:mm:ss');

    registrationId = json['registrationId'];
    registrationStatus = json['registrationStatus'];
    approvedBy = json['approvedBy'];
    expiredDate = json['expiredDate'];
    faceImage = json['faceImage'];
    plateNumber = json['plateNumber'];

    createdAt = json['createdAt'];

  //  createdAt = f.format(json['createdAt'].toUtc()) + " GMT";


    updatedAt = json['updatedAt'];
    model = json['model'];
    registrationNumber = json['registrationNumber'];
    manufacture = json['manufacture'];
    gender = json['gender'];
    userId = json['userId'];
    amount = json['amount'] ?? 30000;
   // price = json['price'] ?? 30000;
  }

  Map<String, dynamic> toJson() {


    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['registrationId'] = this.registrationId;
    data['registrationStatus'] = this.registrationStatus;
    data['approvedBy'] = this.approvedBy;
    data['expiredDate'] = this.expiredDate;
    data['faceImage'] = this.faceImage;
    data['plateNumber'] = this.plateNumber;

    data['createdAt'] = this.createdAt;


    data['updatedAt'] = this.updatedAt;
    data['model'] = this.model;
    data['registrationNumber'] = this.registrationNumber;
    data['manufacture'] = this.manufacture;
    data['gender'] = this.gender;
    data['userId'] = this.userId;
    data['amount'] = this.amount;
    return data;
  }
}
