class Autogenerated {
  int? code;
  Data? data;
  bool? success;

  Autogenerated({this.code, this.data, this.success});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    success = json['success'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['success'] = this.success;
    return data;
  }
}

class Data {
  User? user;
  String? token;

  Data({this.user, this.token});

  Data.fromJson(Map<String, dynamic> json) {
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
    token = json['token'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    data['token'] = this.token;
    return data;
  }
}

class User {
  int? userId;
  String? firstName;
  String? lastName;
  String? phoneNumber;
  dynamic profilePic;
  String? verifyToken;
  bool? isVerified;
  bool? isActive;
  String? createdAt;
  String? updatedAt;

  User(
      {this.userId,
      this.firstName,
      this.lastName,
      this.phoneNumber,
      this.profilePic,
      this.verifyToken,
      this.isVerified,
      this.isActive,
      this.createdAt,
      this.updatedAt});

  User.fromJson(Map<String, dynamic> json) {
    userId = json['userId'];
    firstName = json['firstName'];
    lastName = json['lastName'];
    phoneNumber = json['phoneNumber'];
    profilePic = json['profilePic'];
    verifyToken = json['verifyToken'];
    isVerified = json['isVerified'];
    isActive = json['isActive'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
  }

  // factory User.fromJson(Map<String, dynamic> json) {
  //   return User(
  //   userId : json['userId'] as int,
  //   firstName : json['firstName'] as String,
  //   lastName : json['lastName'] as String,
  //   phoneNumber : json['phoneNumber'] as String,
  //   profilePic : json['profilePic'] as dynamic,
  //   verifyToken : json['verifyToken'] as String,
  //   isVerified : json['isVerified'] as bool,
  //   isActive : json['isActive'] as bool,
  //   createdAt : json['createdAt'] as String,
  //   updatedAt : json['updatedAt'] as String,
  //   );
  // }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['userId'] = this.userId;
    data['firstName'] = this.firstName;
    data['lastName'] = this.lastName;
    data['phoneNumber'] = this.phoneNumber;
    data['profilePic'] = this.profilePic;
    data['verifyToken'] = this.verifyToken;
    data['isVerified'] = this.isVerified;
    data['isActive'] = this.isActive;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    return data;
  }
}