class Autogenerated {
  int? code;
  Data? data;
  bool? success;

  Autogenerated({this.code, this.data, this.success});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    success = json['success'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    if (this.data != null) {

      data['data'] = this.data!.toJson();
  
    }
    data['success'] = this.success;
    return data;
  }
}

class Data {
User? user;

  Data({this.user});

  Data.fromJson(Map<String, dynamic> json) {
    user = json['user'] != null ? new User.fromJson(json['user']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    return data;
  }
}

class User {
  int? userId;
  String? fullName;
  String? username;
 // bool? isActive;
 String? userStatus;
  String? createdAt;
  String? updatedAt;
  int? age;
  String? gender;
  String? address;

  User(
      {this.userId,
      this.fullName,
      this.username,
     // this.isActive,
      this.userStatus,
      this.createdAt,
      this.updatedAt,
      this.age,
      this.gender,
      this.address
      
      });

  User.fromJson(Map<String, dynamic> json) {
    userId = json['userId'];
    fullName = json['userFullName'];
    username = json['username'];
  //  isActive = json['isActive'];
  userStatus = json['userStatus'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    age = json['age'];
    // int ageInt = json['age'] ?? 0;
    // if(ageInt ==0){
    //   age = "";
    // }else{
    //   age = ageInt.toString();
    // }
    
    gender = json['gender'] ?? "";
    address = json['address'] ?? "";
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['userId'] = this.userId;
    data['userFullName'] = this.fullName;
    data['username'] = this.username;
  //  data['isActive'] = this.isActive;
  data['userStatus'] = this.userStatus;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
     data['age'] = this.age;
     data['gender'] = this.gender;
     data['address'] = this.address;
    return data;
  }
}